# Nombre de la aplicación
spring.application.name=sistema-escolar-desafio2

# Configuración de la conexión a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/sistema_escolar_desafio2?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuración de Swagger (Ruta por defecto)
springdoc.swagger-ui.path=/swagger-ui.html